[project]
name = "fraud-detection-features"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pf6511", email = "pfelz@free.fr" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
fraud-detection-features = "fraud_detection_features:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
